name: CI Test & PR dev -> main
on:
  push:
    branches:
    - dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  create-pr:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:

    - uses: actions/checkout@v3
      with:
        branch: main
        fetch-depth: 0

    - name: update local git branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "noreply@github.com"
        git pull origin main
        git reset --hard
        git pull origin dev 
        git commit -am "AUTO merge dev into main"

    - name: PR to main from dev
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_PAT }}
        base: main     # the target branch for PR
#        branch: dev    # source branch
        title: PR dev -> main
        body: |
          ğŸ¤–ğŸ“¦ğŸ Automated PR from dev â†’ main  
          ${{ github.event.head_commit.message }}
        labels: automated
        commit-message: AUTO - dev
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#        delete-branch: true



#  release-to-pypi-test:
#    name: Release to PyPI Test
#    runs-on: ubuntu-latest
##    needs: run-tests
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: '3.10'
#    - name: Install poetry
#      run: pip install poetry==1.2.1
#    - uses: bjoluc/semantic-release-config-poetry@v2
#      with:
#        pypi_token: ${{ secrets.TEST_PYPI_API_KEY }}
#        pypi_repository: https://test.pypi.org/legacy/
#        release_branch: dev

